import { useMemo, useRef, useState } from 'react';
import { Alert, Linking, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import * as Crypto from 'expo-crypto';
import * as ImagePicker from 'expo-image-picker';
import SignatureCanvas, { type SignatureViewRef } from 'react-native-signature-canvas';
import { Screen } from '@/components/Screen'; import { Card } from '@/components/Card';
import { defaultChecklist, type ChecklistItem, type ChecklistStatus, type MobileCommand, type Schedule, type ScheduleStatus } from '@/contracts';
import { enqueueCommand, enqueueUpload, getEntity, upsertEntity } from '@/database'; import { useAppStore } from '@/store'; import { colors } from '@/theme';
import { isChecklistIncomplete, scheduleTransitions } from '@/orderRules';

const statuses: ChecklistStatus[] = ['OK', 'N/OK', 'N/A'];

export default function OrderDetails() {
  const { id } = useLocalSearchParams<{ id: string }>(); const refresh = useAppStore(state => state.refreshLocal); const sync = useAppStore(state => state.sync);
  const initial = getEntity<Schedule>('schedule', id); const [schedule, setSchedule] = useState(initial); const [checklist, setChecklist] = useState<ChecklistItem[]>(initial?.checklist?.length ? initial.checklist : defaultChecklist); const [imei, setImei] = useState(initial?.installedImei || ''); const [frustrationReason, setFrustrationReason] = useState(''); const [clientSignature, setClientSignature] = useState(''); const [techSignature, setTechSignature] = useState(''); const [signatureMode, setSignatureMode] = useState<'client' | 'technician' | null>(null); const signatureRef = useRef<SignatureViewRef>(null);
  const inventory = useAppStore(state => state.inventory); const selectedInventory = useMemo(() => inventory.find(item => item.imei === imei), [inventory, imei]);
  if (!schedule) return <Screen title="OS não encontrada"><Text style={styles.muted}>Sincronize novamente para carregar esta OS.</Text></Screen>;

  const queue = (type: MobileCommand['type'], payload: Record<string, unknown>, localPatch: Partial<Schedule>) => {
    const command: MobileCommand = { commandId: Crypto.randomUUID(), type, entityId: schedule.id, baseVersion: schedule.version || 0, createdAt: Date.now(), payload };
    enqueueCommand(command); const next = { ...schedule, ...localPatch, version: Number(schedule.version || 0) + 1, updatedAt: Date.now() }; upsertEntity('schedule', next); setSchedule(next); refresh(); void sync();
  };
  const changeStatus = (status: ScheduleStatus) => {
    if (status === 'Frustrada') { if (frustrationReason.trim().length < 3) return Alert.alert('Motivo obrigatório', 'Descreva o motivo antes de marcar o atendimento como frustrado.'); queue('schedule.status', { status, reason: frustrationReason.trim() }, { status }); return; }
    queue('schedule.status', { status }, { status });
  };
  const updateItem = (index: number, field: 'before' | 'after', value: ChecklistStatus) => setChecklist(items => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const takePhoto = async (index: number, field: 'beforePhoto' | 'afterPhoto') => { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) return Alert.alert('Câmera', 'Permita o uso da câmera para registrar evidências.'); const result = await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.7 }); if (!result.canceled) { const asset = result.assets[0]; const token = enqueueUpload(asset.uri, 'checklist', asset.mimeType || 'image/jpeg'); setChecklist(items => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: token } : item)); } };
  const saveChecklist = () => { queue('schedule.checklist', { checklist }, { checklist }); Alert.alert('Salvo', 'Checklist salvo no aparelho e colocado na fila de sincronização.'); };
  const complete = () => {
    const incomplete = isChecklistIncomplete(checklist);
    if (incomplete) return Alert.alert('Checklist incompleto', 'Preencha entrada e saída. Itens N/OK precisam de observação e foto.');
    if (!clientSignature || !techSignature) return Alert.alert('Assinaturas', 'Colete as assinaturas do cliente e do técnico.');
    queue('schedule.complete', { checklist, installedImei: imei, inventoryItemId: selectedInventory?.id, clientSignature, technicianSignature: techSignature, signedAt: Date.now(), signatureEvidence: { signerName: schedule.clientName || 'Cliente', consentVersion: 'mobile-v1', capturedOffline: true } }, { status: 'AGUARDANDO VÍNCULO', checklist, installedImei: imei });
    Alert.alert('OS finalizada', 'A OS foi salva e será confirmada pela central após sincronizar.', [{ text: 'OK', onPress: () => router.back() }]);
  };

  if (signatureMode) return <Screen title={signatureMode === 'client' ? 'Assinatura do cliente' : 'Assinatura do técnico'}><View style={styles.signature}><SignatureCanvas ref={signatureRef} onOK={value => { signatureMode === 'client' ? setClientSignature(value) : setTechSignature(value); setSignatureMode(null); }} descriptionText="Assine no espaço acima" clearText="Limpar" confirmText="Salvar" webStyle=".m-signature-pad--footer {display:flex; gap:8px;}"/></View><TouchableOpacity style={styles.secondary} onPress={() => setSignatureMode(null)}><Text style={styles.secondaryText}>CANCELAR</Text></TouchableOpacity></Screen>;

  return <Screen title={schedule.vehiclePlate} right={<TouchableOpacity onPress={() => router.back()}><Text style={styles.close}>FECHAR</Text></TouchableOpacity>}>
    <Card><Text style={styles.status}>{schedule.status}</Text><Text style={styles.heading}>{schedule.vehicleModel}</Text><Text style={styles.muted}>{schedule.serviceType} · {schedule.deviceType}</Text><Text style={styles.client}>{schedule.clientName}</Text><Text style={styles.muted}>{schedule.locationAddress}</Text><View style={styles.row}><TouchableOpacity style={styles.link} onPress={() => Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(schedule.locationAddress)}`)}><Text style={styles.linkText}>NAVEGAR</Text></TouchableOpacity>{schedule.clientPhone ? <TouchableOpacity style={styles.link} onPress={() => Linking.openURL(`tel:${schedule.clientPhone}`)}><Text style={styles.linkText}>LIGAR</Text></TouchableOpacity> : null}</View></Card>
    {(scheduleTransitions[schedule.status] || []).length ? <Card><Text style={styles.section}>PRÓXIMA ETAPA</Text>{(scheduleTransitions[schedule.status] || []).includes('Frustrada') && <TextInput value={frustrationReason} onChangeText={setFrustrationReason} placeholder="Motivo caso o serviço seja frustrado" placeholderTextColor={colors.muted} style={styles.input}/>}<View style={styles.wrap}>{(scheduleTransitions[schedule.status] || []).map(status => <TouchableOpacity key={status} style={[styles.action, status === 'Frustrada' && styles.danger]} onPress={() => changeStatus(status)}><Text style={styles.actionText}>{status}</Text></TouchableOpacity>)}</View></Card> : null}
    <Card><Text style={styles.section}>EQUIPAMENTO UTILIZADO</Text><TextInput value={imei} onChangeText={setImei} placeholder="IMEI" placeholderTextColor={colors.muted} style={styles.input}/><Text style={styles.muted}>{selectedInventory ? `${selectedInventory.type} · ${selectedInventory.status}` : 'Informe um IMEI disponível no seu estoque.'}</Text></Card>
    <Text style={styles.section}>CHECKLIST DE ENTRADA E SAÍDA</Text>{checklist.map((item, index) => <Card key={item.id || item.name}><Text style={styles.itemName}>{item.name}</Text>{(['before', 'after'] as const).map(field => <View key={field} style={styles.checkRow}><Text style={styles.phase}>{field === 'before' ? 'ENTRADA' : 'SAÍDA'}</Text>{statuses.map(value => <TouchableOpacity key={value} onPress={() => updateItem(index, field, value)} style={[styles.pill, item[field] === value && styles.pillActive]}><Text style={[styles.pillText, item[field] === value && styles.pillTextActive]}>{value}</Text></TouchableOpacity>)}<TouchableOpacity onPress={() => takePhoto(index, field === 'before' ? 'beforePhoto' : 'afterPhoto')} style={styles.photo}><Text style={styles.photoText}>{item[field === 'before' ? 'beforePhoto' : 'afterPhoto'] ? '✓ FOTO' : '+ FOTO'}</Text></TouchableOpacity></View>)}{[item.before, item.after].includes('N/OK') ? <TextInput value={item.notes || ''} onChangeText={notes => setChecklist(items => items.map((current, itemIndex) => itemIndex === index ? { ...current, notes } : current))} placeholder="Descreva o problema" placeholderTextColor={colors.muted} style={styles.input}/> : null}</Card>)}
    <TouchableOpacity style={styles.secondary} onPress={saveChecklist}><Text style={styles.secondaryText}>SALVAR CHECKLIST</Text></TouchableOpacity>
    {schedule.status === 'EM EXECUÇÃO' ? <Card><Text style={styles.section}>ASSINATURAS</Text><View style={styles.row}><TouchableOpacity style={styles.link} onPress={() => setSignatureMode('client')}><Text style={styles.linkText}>{clientSignature ? '✓ CLIENTE' : 'ASSINAR CLIENTE'}</Text></TouchableOpacity><TouchableOpacity style={styles.link} onPress={() => setSignatureMode('technician')}><Text style={styles.linkText}>{techSignature ? '✓ TÉCNICO' : 'ASSINAR TÉCNICO'}</Text></TouchableOpacity></View><TouchableOpacity style={styles.finish} onPress={complete}><Text style={styles.finishText}>FINALIZAR E ENVIAR PARA A CENTRAL</Text></TouchableOpacity></Card> : null}
  </Screen>;
}
const styles = StyleSheet.create({ close: { color: colors.muted, fontWeight: '900' }, status: { color: colors.primary, fontSize: 11, fontWeight: '900' }, heading: { color: colors.text, fontSize: 22, fontWeight: '900' }, client: { color: colors.text, fontSize: 16, fontWeight: '800' }, muted: { color: colors.muted }, row: { flexDirection: 'row', gap: 8, alignItems: 'center' }, wrap: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' }, link: { borderColor: colors.primary, borderWidth: 1, borderRadius: 10, padding: 10 }, linkText: { color: colors.primary, fontSize: 11, fontWeight: '900' }, section: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, action: { backgroundColor: colors.blue, borderRadius: 12, padding: 13 }, danger: { backgroundColor: colors.danger }, actionText: { color: colors.text, fontWeight: '900', fontSize: 11 }, input: { backgroundColor: colors.cardLight, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 13, color: colors.text }, itemName: { color: colors.text, fontWeight: '900', fontSize: 16 }, checkRow: { flexDirection: 'row', alignItems: 'center', gap: 5, flexWrap: 'wrap' }, phase: { color: colors.muted, fontSize: 9, fontWeight: '900', width: 48 }, pill: { borderColor: colors.border, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 9 }, pillActive: { backgroundColor: colors.primary, borderColor: colors.primary }, pillText: { color: colors.muted, fontSize: 10, fontWeight: '900' }, pillTextActive: { color: '#052e16' }, photo: { padding: 7 }, photoText: { color: colors.blue, fontSize: 10, fontWeight: '900' }, secondary: { borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 15, alignItems: 'center' }, secondaryText: { color: colors.text, fontWeight: '900' }, finish: { backgroundColor: colors.primary, borderRadius: 14, padding: 16, alignItems: 'center', marginTop: 8 }, finishText: { color: '#052e16', fontWeight: '900', fontSize: 11 }, signature: { height: 450, backgroundColor: 'white', borderRadius: 18, overflow: 'hidden' } });
