import { useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { Screen } from '@/components/Screen'; import { Card } from '@/components/Card'; import { api } from '@/api'; import { useAppStore } from '@/store'; import { colors, money } from '@/theme';

export default function Invoices() {
  const { schedules, invoices, sync } = useAppStore(); const [selected, setSelected] = useState<string[]>([]); const [number, setNumber] = useState(''); const [issueDate, setIssueDate] = useState(new Date().toISOString().slice(0, 10)); const [amount, setAmount] = useState(''); const [documents, setDocuments] = useState<DocumentPicker.DocumentPickerAsset[]>([]); const [sending, setSending] = useState(false);
  const eligible = useMemo(() => schedules.filter(item => ['CONCLUÍDA', 'VALIDADA'].includes(item.status) && !item.technicianInvoiceId), [schedules]);
  const calculated = eligible.filter(item => selected.includes(item.id)).reduce((sum, item) => sum + Number(item.technicianPaymentAmount || 0), 0);
  const chooseDocument = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ['application/pdf', 'application/xml', 'text/xml', 'image/jpeg', 'image/png'], multiple: true, copyToCacheDirectory: true }); if (!result.canceled) setDocuments(current => [...current, ...result.assets].slice(0, 3)); };
  const submit = async () => { if (!selected.length || !number.trim() || !Number(amount) || !documents.length) return Alert.alert('Dados incompletos', 'Selecione OS, informe número/valor e anexe ao menos um documento.'); setSending(true); try { const attachments = []; for (const document of documents) attachments.push((await api.upload(document.uri, 'invoice', document.mimeType || 'application/pdf')).id); await api.createInvoice({ number, issueDate, amount: Number(amount), scheduleIds: selected, attachmentIds: attachments }); setSelected([]); setNumber(''); setAmount(''); setDocuments([]); await sync(); Alert.alert('Nota enviada', 'A central já pode conferir os documentos.'); } catch (error: any) { Alert.alert('Falha ao enviar', error?.message || 'Verifique sua conexão.'); } finally { setSending(false); } };
  return <Screen title="Notas fiscais"><Card><Text style={styles.section}>NOVA NOTA · LOTE DE OS</Text>{eligible.map(item => <TouchableOpacity key={item.id} onPress={() => setSelected(value => value.includes(item.id) ? value.filter(id => id !== item.id) : [...value, item.id])} style={styles.schedule}><Text style={styles.checkbox}>{selected.includes(item.id) ? '☑' : '☐'}</Text><View><Text style={styles.plate}>{item.vehiclePlate}</Text><Text style={styles.muted}>{item.osNumber || item.id} · {money(Number(item.technicianPaymentAmount || 0))}</Text></View></TouchableOpacity>)}{!eligible.length ? <Text style={styles.muted}>Nenhuma OS elegível para faturamento.</Text> : null}<Text style={styles.total}>Total das OS: {money(calculated)}</Text><TextInput value={number} onChangeText={setNumber} placeholder="Número da nota" placeholderTextColor={colors.muted} style={styles.input}/><TextInput value={issueDate} onChangeText={setIssueDate} placeholder="AAAA-MM-DD" placeholderTextColor={colors.muted} style={styles.input}/><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="Valor da nota" placeholderTextColor={colors.muted} style={styles.input}/><TouchableOpacity style={styles.secondary} onPress={chooseDocument}><Text style={styles.secondaryText}>ANEXAR XML, PDF OU FOTO ({documents.length}/3)</Text></TouchableOpacity><TouchableOpacity disabled={sending} style={styles.primary} onPress={submit}><Text style={styles.primaryText}>{sending ? 'ENVIANDO...' : 'ENVIAR PARA CONFERÊNCIA'}</Text></TouchableOpacity></Card><Text style={styles.section}>HISTÓRICO</Text>{invoices.map(invoice => <Card key={invoice.id}><View style={styles.between}><Text style={styles.plate}>NF {invoice.number}</Text><Text style={[styles.badge, invoice.status === 'approved' ? styles.approved : invoice.status === 'rejected' ? styles.rejected : styles.pending]}>{invoice.status.toUpperCase()}</Text></View><Text style={styles.total}>{money(invoice.amount)}</Text><Text style={styles.muted}>{invoice.issueDate} · {invoice.scheduleIds.length} OS</Text>{invoice.rejectionReason ? <Text style={styles.reason}>{invoice.rejectionReason}</Text> : null}</Card>)}</Screen>;
}
const styles = StyleSheet.create({ section: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, schedule: { flexDirection: 'row', gap: 10, alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, paddingVertical: 9 }, checkbox: { color: colors.primary, fontSize: 22 }, plate: { color: colors.text, fontWeight: '900', fontSize: 16 }, muted: { color: colors.muted, fontSize: 12 }, total: { color: colors.text, fontWeight: '800' }, input: { backgroundColor: colors.cardLight, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 13, color: colors.text }, secondary: { borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 13, alignItems: 'center' }, secondaryText: { color: colors.text, fontWeight: '900', fontSize: 10 }, primary: { backgroundColor: colors.primary, borderRadius: 12, padding: 15, alignItems: 'center' }, primaryText: { color: '#052e16', fontWeight: '900', fontSize: 10 }, between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, badge: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, overflow: 'hidden', color: colors.text, fontSize: 9, fontWeight: '900' }, approved: { backgroundColor: '#166534' }, rejected: { backgroundColor: '#991b1b' }, pending: { backgroundColor: '#92400e' }, reason: { color: colors.danger, fontWeight: '700' } });
